INSERT INTO programs (
  id, university_id, name, degree_level, subject_area, tuition_fee, tuition_currency, intake_months_json, is_active
) VALUES
(1, 1, 'AI & Data Science', 'bachelors', 'IT & Game Design', 726.00, 'EUR', '["September"]', 1),
(2, 1, 'Business Management', 'bachelors', 'Business & Management', 726.00, 'EUR', '["September"]', 1),
(3, 2, 'Business Administration', 'bachelors', 'Business & Management', 3500.00, 'EUR', '["September"]', 1),
(4, 2, 'MBA', 'masters', 'Business & Management', 6000.00, 'EUR', '["September"]', 1),
(5, 3, 'Doctor of Medicine (MD)', 'phd', 'Medicine & Health', 32000.00, 'USD', '["January","April","August"]', 1),
(6, 3, 'Public Health', 'masters', 'Medicine & Health', 25000.00, 'USD', '["January","August"]', 1),
(7, 4, 'MBA', 'masters', 'Business & Management', 36000.00, 'USD', '["January","August"]', 1),
(8, 4, 'Computer Science', 'bachelors', 'IT & Game Design', 34000.00, 'USD', '["January","August"]', 1),
(9, 5, 'Business Administration', 'bachelors', 'Business & Management', 34000.00, 'USD', '["January","August"]', 1),
(10, 5, 'Nursing', 'bachelors', 'Medicine & Health', 38000.00, 'USD', '["January","August"]', 1),
(11, 6, 'Sustainable Energy', 'masters', 'Engineering', 12000.00, 'EUR', '["September"]', 1),
(12, 6, 'Energy Innovation', 'masters', 'Engineering', 18000.00, 'EUR', '["September"]', 1),
(13, 7, 'Graphic Design', 'bachelors', 'Design & Creative Arts', 8000.00, 'EUR', '["September","February"]', 1),
(14, 7, 'Interior Architecture', 'masters', 'Design & Creative Arts', 14000.00, 'EUR', '["September","February"]', 1),
(15, 8, 'Bachelor in Management', 'bachelors', 'Business & Management', 9000.00, 'EUR', '["September","January"]', 1),
(16, 8, 'Master in Management', 'masters', 'Business & Management', 16000.00, 'EUR', '["September","January"]', 1),
(17, 9, 'Hospitality Management', 'bachelors', 'Hospitality', 7000.00, 'EUR', '["February","September"]', 1),
(18, 9, 'Business Administration', 'bachelors', 'Business & Management', 6500.00, 'EUR', '["February","September"]', 1),
(19, 10, 'International Business', 'bachelors', 'Business & Management', 8500.00, 'EUR', '["September","February"]', 1),
(20, 10, 'Marketing', 'masters', 'Business & Management', 13000.00, 'EUR', '["September","February"]', 1),
(21, 11, 'Culinary Arts', 'diploma', 'Hospitality', 4500.00, 'EUR', '["February","September"]', 1),
(22, 11, 'Hotel Management', 'diploma', 'Hospitality', 8000.00, 'EUR', '["February","September"]', 1),
(23, 12, 'Business Administration', 'bachelors', 'Business & Management', 18000.00, 'USD', '["January","March","June","August","October"]', 1),
(24, 12, 'MBA', 'masters', 'Business & Management', 28000.00, 'USD', '["January","March","June","August","October"]', 1)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  degree_level = VALUES(degree_level),
  subject_area = VALUES(subject_area),
  tuition_fee = VALUES(tuition_fee),
  tuition_currency = VALUES(tuition_currency),
  intake_months_json = VALUES(intake_months_json),
  is_active = VALUES(is_active);
